new param for EM100 BMC #114
opencomputeproject/OSF-OSFCI pull request #116
Opened 2024-08-23 14:02 UTC by arunkoshy

2024-08-23 14:03 UTC, arunkoshy commented
@vejmarie tested/via with @gregg-shick

2024-08-23 15:58 UTC, gregg-shick approved these changes

2024-08-26 18:21 UTC, vejmarie requested changes

2024-08-26 19:11 UTC, arunkoshy commented on ctrl/ctrl1.go
> +			args = append(args, em100BmcArg)
refactoring based on your note @vejmarie - thank you.

2024-08-26 19:52 UTC, arunkoshy commented
@vejmarie please check - this is now deployed on dev/ctrl10 - all is well.

2024-08-27 10:07 UTC, vejmarie approved these changes

2024-08-27 10:07 UTC, merged