Contest Framework: Support to download the test logs
opencomputeproject/OSF-OSFCI pull request #43
Opened 2022-05-03 23:20 UTC by susmithp

Added the support for downloading the contest test log files.

2022-05-04 00:48 UTC, arunkoshy requested changes

2022-05-04 00:48 UTC, arunkoshy commented on misc/contest/contestcli.go
>  	loghandler, err := os.OpenFile(logFile, os.O_CREATE|os.O_APPEND|os.O_RDWR, 0666)
@susmithp let's get this reworked based on discussion offline.

2022-05-04 00:57 UTC, arunkoshy requested changes

2022-05-04 00:57 UTC, arunkoshy commented on misc/contest/contestcli.go
> +		outhandler, _ := os.OpenFile(outfile, os.O_CREATE|os.O_APPEND|os.O_RDWR, 0666)
@susmithp ditto to prior check -- let's discuss for this and ctrl1 situation

2022-05-06 02:14 UTC, arunkoshy approved these changes
LGTM @vejmarie

2022-05-06 03:11 UTC, arunkoshy commented on gateway/js/contest.js
> +                                link.download="contest_log.zip";
@susmithp we will refactor this to reflect the date/time stamp bits from the server location.

2022-05-06 03:13 UTC, arunkoshy approved these changes

2022-05-06 19:23 UTC, vejmarie approved these changes

2022-05-06 19:24 UTC, arunkoshy commented on ctrl/ctrl1.go
> +		cmd := exec.Command("/bin/sh", "-c", command)
@susmithp candidate for refactoring as per discussion offline

2022-05-06 19:50 UTC, merged